### ISSUE TITLE
SHA of just the identifier

### ISSUE THREAD

**Issue by valentinedwv** [gleanerio/gleaner#124]
The SHA is for the full JSON. This means that if a file uses some changing value, like a date published being when the page was  sent to browser that the SHA will change. (I know, we did that in a project a long long time ago when dublin core was king).

Think that would should define an 'identifier' template for a repository, and  utilize that as the identifier SHA.
This was what was done for ISO data catalogs (aka geoportal), and the biocaddie project. 

We can and should probably store the entire file sha.

**Comment by nein09** [comment]
Oh hmm, yeah- it's the difference between a PID and an ID. If we just want to know whether we indexed this before, and not whether it's perfectly identical to the last one we indexed, this is a good idea.

**Comment by valentinedwv** [comment]
Getting some identifiers using JSONPath. So the repository could have some custom jsonpath, or just use some default one.
https://github.com/gleanerio/gleaner/blob/fix_124_identifiers_sha/internal/common/identifier_test.go

**Comment by valentinedwv** [comment]
This technique is causing a bug when a file has two JSONLD.

https://github.com/gleanerio/gleaner/issues/124

Suggesting that we use identifiers, checking for unchanged, is
* get identifier,
* search for item in s3
* sha whole file and check against X-meta-sha field in s3.
* ?do we add a checked date x-meta-?
