### ISSUE TITLE
Address JSON-LD being an array of 1 or more graphs

### ISSUE THREAD

**Issue by fils** [gleanerio/gleaner#128]
In cases like at:

https://oceanscape.org/organisation/deep-ocean-stewardship-initiative/

```
[{
	"@context": "https://schema.org",
	"@type": "Organization",
	"@id": "https://oceanscape.org/organisation/deep-ocean-stewardship-initiative/#Organization",
	"url": "https://oceanscape.org/organisation/deep-ocean-stewardship-initiative/",
	"description": "",
	"name": "Deep-Ocean Stewardship Initiative",
	"address": {
		"streetAddress": "University of Southampton, Waterfront Campus, European Way, Southampton, UK",
		"addressCountry": ""
	},
	"logo": "https://oceanscape.org/wp-content/uploads/2019/09/DOSI-Logo.jpg",
	"knowsAbout": "Advocating for (ocean) science, Defining strategies/road maps/priorities for Earth (ocean) observing/science, Providing scientific advice for policy makers"
}]
```

This array could be 1 or more graphs.

Gleaner needs to detect arrays and then process each item.

Related, could we provide a list of top level types to index?  This would require introspection and be slow, so really this should be in Nabu.

**Comment by nein09** [comment]
Some of the things I'm indexing for POLDER search are like this, and it seems to work okay, but it's shaped slightly differently. I'm thinking specifically of http://hedeby.uwaterloo.ca/api/metadata?page=1 and its subsequent pages.

**Comment by valentinedwv** [comment]
Yes, EC sees things that are being done as 'DataCatalog's so they contain multiple 'Datasets' and that needs to be handled in some manner.

**Comment by valentinedwv** [comment]
#121 is another example

**Comment by fils** [comment]
@nein09 So graphs shaped like the following are working OK for you?  The example you shared doesn't have the root level [] surrounding the package though.  That is the issue that is showing up.

@valentinedwv I have a fix for this sitting in some off-line code, I can work this in.

source: view-source:https://pogo-ocean.org/pogo-member/ird-institut-de-recherche-pour-le-developpement/

```json
[{
	"@context": "https://schema.org/",
	"@type": "Organization",
	"name": "Partnership for Observation of the Global Ocean",
	"url": "https://www.ird.fr/",
	"sameAs": [],
	"logo": {
		"@type": "ImageObject",
		"url": "https://pogo-ocean.org/wp-content/uploads/2022/10/logo_IRD_2016_LONGUEUR_FR_BLANC_coloured.png",
		"width": 1451,
		"height": 337
	},
	"address": {
		"streetAddress": "Research Institute for Development, Boulevard de Dunkerque, Marseille, France"
	},
	"image": [{
		"@type": "ImageObject",
		"@id": "https://pogo-ocean.org/pogo-member/ird-institut-de-recherche-pour-le-developpement/#primaryimage",
		"url": "https://pogo-ocean.org/wp-content/uploads/2022/10/logo_IRD_2016_LONGUEUR_FR_BLANC_coloured.png",
		"width": "1451",
		"height": "337"
	}]
}]
```

**Comment by nein09** [comment]
@fils I'm not sure- I can tell you that something like this is fine, though:

```
{
 "@context": {
   "@vocab":"https://schema.org/"
  }, 
  "@type":"ItemList", 
  "itemListElement": [
   { 
      "@type":"ListItem", 
      "position":1, 
      "item":{ 
           "@type":"Dataset",
           "name": "dataset name" // it looks like they usually do inside here
       },
   },
   { "@type":"ListItem", "position":2, "item":{ "@type":"Dataset", ... you get the idea }
   }
  ]
}
```

**Comment by fils** [comment]
This issue seems to be in the file https://github.com/gleanerio/gleaner/blob/dev/internal/summoner/acquire/jsonutils.go where isValid and addToJsonListIfValid needs to address the [json] approach

**Comment by valentinedwv** [comment]
opencore?

{"contentType":"json or ld_json","file":"/Users/valentin/development/dev_earthcube/gleanerio/gleaner/internal/summoner/acquire/acquire.go:243","func":"github.com/gleanerio/gleaner/internal/summoner/acquire.FindJSONInResponse","level":"error","msg":"Error processing json response from https://opencoredata.org/id/csdco/do/017f759f3ad12d047a10e192fb416f5a387db9f4e723cdb82cd36be70ddd4c47.jsonlderror checking for valid json: Error in unmarshaling json: json: cannot unmarshal array into Go value of type map[string]interface {}","time":"2023-05-02T19:34:58Z","url":"https://opencoredata.org/id/csdco/do/017f759f3ad12d047a10e192fb416f5a387db9f4e723cdb82cd36be70ddd4c47.jsonld"}
{"contentType":"json or ld_json","file":"/Users/valentin/development/dev_earthcube/gleanerio/gleaner/internal/summoner/acquire/acquire.go:243","func":"github.com/gleanerio/gleaner/internal/summoner/acquire.FindJSONInResponse","level":"error","msg":"Error processing json response from https://opencoredata.org/id/csdco/do/018db36337e931d232f7d7bbb73fd624c8e0fadb48d7aa4c6d4c70c780f08294.jsonlderror checking for valid json: Error in unmarshaling json: json: cannot unmarshal array into Go value of type map[string]interface {}","time":"2023-05-02T19:34:58Z","url":"https://opencoredata.org/id/csdco/do/018db36337e931d232f7d7bbb73fd624c8e0fadb48d7aa4c6d4c70c780f08294.jsonld"}
