### ISSUE TITLE
Chrome DevTools wants us to use 'PUT' not 'GET'

### ISSUE THREAD

**Issue by nein09** [gleanerio/gleaner#174]
I see a lot of this in my logs:

{"file":"/home/runner/work/gleaner/gleaner/internal/summoner/acquire/headlessNG.go:219","func":"github.com/gleanerio/gleaner/internal/summoner/acquire.PageRender","issue":"Not REPO FAULT. Devtools... Is Headless Container running?","level":"error","msg":"devtool: CreateURL: Using unsafe HTTP verb GET to invoke /json/new. This action supports only PUT verb.","time":"2023-03-16T20:25:08Z","url":"https://data.g-e-m.dk/Datasets?doi=10.17897/CG48-0H12"}

This is using `chromedp/headless-shell:stable`

A little googling got me this, which suggests changing 'Get' to 'Put': https://danielcompton.net/snippets/chrome-devtools-unsafe-http-verb

**Comment by nein09** [comment]
Annoyingly, this seems to be coming from inside `devtool` so there isn't much we can do. https://pkg.go.dev/github.com/mafredri/cdp/devtool#DevTools.Create

**Comment by valentinedwv** [comment]
may be fixed.
https://github.com/mafredri/cdp/commit/0a8c15b2178508e9ae038803b3aa957333f0cbc9
