### ISSUE TITLE
add summary namespace to config

### ISSUE THREAD

**Issue by MBcode** [gleanerio/gleaner#180]
Right now the nabu file has:
sparql:
        endpoint:
and I am proposing adding something like
        summary:
so my [crawl-test](https://github.com/earthcube/ec/tree/master/test/crawl) can parse that elt out and use it to get the counts in that namespace, which is presently created off the main endpoint-namespace via a [materialization process](https://github.com/earthcube/earthcube_utilities/blob/main/summarize/src/materialize_summary.py)

This could become a wider discussion of how this process will be integrated into the gleaner/nabu workflow

**Comment by valentinedwv** [comment]
handled in dagster
