### ISSUE TITLE
Could you add a LICENSE file?

### ISSUE THREAD

**Issue by danbri** [gleanerio/gleaner#23]
Something like https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository ? (I think maybe also needed in other projects nearby here?)

**Comment by fils** [comment]
Added a GPL 3 license..   

Note..  original work to this point was funded by NSF, so was implicate CC0.

Work funded by UN requested GPL.

**Comment by ahayes** [comment]
Hey Doug. Are you willing to multi-license under a non copyleft as well? Can't bring it into BSD/MIT/Apache/Mozilla/Eclipse projects with GPL the only license.

**Comment by fils** [comment]
I am ..  and I am new to this licensing too..   so if you provide me guidance I am happy to do this.

I was going to just use CC0    but some other people asked me to do GPL..   

Honestly, I don't know all the ins and outs of this so if you can provide guidance I'm happy to do it.

I got some funds to work on Gleaner again with the UN, so I'm looking forward to getting back into this code and cleaning it and improving it.

**Comment by fils** [comment]
Going to re-open to resolve this...
