### ISSUE TITLE
SIGSEGV - segmentation violation

### ISSUE THREAD

**Issue by ACz-UniBi** [gleanerio/gleaner#25]
Hi,

I've a interesting issue with the 'gleaner' command, which is a static exe file.

The gleaner cmd compiled from source has the same SIGSEGV message runtime panic message as the v2.0.25 and v2.0.22 I downloaded from GitHub here.

The message are:

v2.0.22
```
main.go:30: EarthCube Gleaner
panic: runtime error: invalid memory address or nil pointer dereference
```

v2.0.25
```
main.go:34: EarthCube Gleaner
panic: runtime error: invalid memory address or nil pointer dereference
```

self compiled version
```
main.go:35: EarthCube Gleaner
panic: runtime error: invalid memory address or nil pointer dereference

```

I try to execute the gleaner cmd with and without _root_ permission. The results are the same.
Does any one have/had similar issues in the past and a hint to solve this?

OS: Ubuntu 20.04
GOLANG: go version go1.13.8 linux/amd64
Environment variables: GLEANER_BASE=/tmp/gleaner GLEANER_OBJECTS=/tmp/gleaner/datavol/s3 GLEANER_GRAPH=/tmp/gleaner/datavol/graph DATAVOL=/tmp/gleaner/datavol and directories exists.

Thanks in advance, Andreas

**Comment by fils** [comment]
@ACz-UniBi 

Really sorry I missed this..  I do a bad job following issues sometimes..  feel free to tag me in issues!   I at least see those.  :)  

I'll take a look at this.   It might be that I'm not dealing with command line flag issues well enough..  (my fault.  I need to work on that).  

Take a look at:

https://book.oceaninfohub.org/indexing/qstart.html  (gleaner from command line)

https://book.oceaninfohub.org/indexing/cliDocker/README.html  (uses a new Gleaner in Docker approach)

This is some documentation I am working on now for another group that is going to use this.    I'm still working on that documentation still..  but it's getting there.  

I'll try and dive into this issue next week and get it resolved for you.  Sorry for the delay!

**Comment by fils** [comment]
@ACz-UniBi 

Working on some screen casts for another group..  pass this one along in case it's interesting.  It's for the Dockerized version of gleaner and you were just running the built binary, but similar approaches.  

https://youtu.be/UqeJBcrJzZw

**Comment by ACz-UniBi** [comment]
@fils 

Thank you very much to provide the links! I'll check and try it out, e.g. in a docker environment. Please provide further screencasts or/and notes here also if available.

**Comment by fils** [comment]
@ACz-UniBi several videos have been made to support the broader topics being developed at https://book.oceaninfohub.org/

When these are published somewhere I will document that and let you know.   I've moved all the related work into one org at github at https://github.com/gleanerio will focus work there now.  Lot's of documentation updates to do.  

Let me know how it works..  happy to help and make fixes and documentation improvements for you.

**Comment by valentinedwv** [comment]
Closing. we now have binaries, and a docker, so hopefully resolved
