### ISSUE TITLE
Bug in current robots.txt library

### ISSUE THREAD

**Issue by nein09** [gleanerio/gleaner#90]
Well, this is frustrating.

The current robots.txt library behaves in a way that it interprets `Disallow: ` as "disallow everything", which is buggy. That actually means "allow everything"

I found this while indexing CCHDO with robots support on (https://cchdo.ucsd.edu/robots.txt )

I then noticed that it's been a while since the maintainer has updated the library we're currently using. We should probably include one that's more actively developed, like https://github.com/temoto/robotstxt or https://github.com/jimsmart/grobotstxt

I'll make the switch, but this is so annoying!

**Comment by valentinedwv** [comment]
Merged. Closing
