### ISSUE TITLE
allow for small fixes to jsonld (context), to allow conversion

### ISSUE THREAD

**Issue by MBcode** [gleanerio/gleaner#92]
Sometimes I would like to load a set of jsonld before I wait for the authors to fix and rerun their template.  I have an extruct based workflow, where I just insert a fix.sed file, but do not know how this might work w/gleaner's conversion.  I guess it would have to happen before (or because of) catching the problem (in the jsonld).

eg. a recent run of [unidata](http://earthcube.ddns.net/ec/unidata/)

**Comment by valentinedwv** [comment]
issues #129 #130
